baseURL: "https://blog.metal-detector.rocks/"
languageCode: "en-us"
title: "Metal Detector Blog"
theme: "PaperMod"
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Metal Detector Blog"
  description: "Built for Metalheads."
  author: ["DanielW", "NilsD"]
  images: ["https://metal-detector.rocks/images/logo.png"]

  defaultTheme: dark # dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: false
  disableSpecial1stPost: false
  comments: true
  hidemeta: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "/favicon.png"
    favicon16x16: "/favicon.png"
    favicon32x32: "/favicon.png"
    apple_touch_icon: "/favicon.png"
    safari_pinned_tab: "/favicon.png"
    disableFingerprinting: true

  label:
    text: " "
    icon: /logo.png
    iconHeight: 70

  homeInfoParams:
    Title: Metal Detector Blog
    Content: "Built for Metalheads."

  socialIcons:
    - name: buymeacoffee
      url: "https://www.buymeacoffee.com/metaldetector"
    - name: instagram
      url: "https://instagram.com/metaldetector.rocks"
    - name: github
      url: "https://github.com/MetalDetectorRocks"
    - name: rss
      url: "index.xml"

#  analytics:
#    google:
#      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: metal-detector
      name: Main Site
      url: https://metal-detector.rocks
      weight: 20
#    - identifier: categories
#      name: Categories
#      url: /categories/
#      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: archive
      name: Archive
      url: /archive/
      weight: 40
    - identifier: search
      name: Search
      url: /search/
      weight: 50

outputs:
  home:
    - HTML
    - RSS
    - JSON
